name: vimeo_embed_webview_player
description: A Flutter package for embedding Vimeo videos using WebView with autoplay and customization support for iOS and macOS.
version: 0.0.3
homepage: https://github.com/5alafawyyy/vimeo_embed_webview_player
repository: https://github.com/yourusername/vimeo_embed_webview_player

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  webview_flutter_wkwebview: ^3.17.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
